In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(color_codes=True)

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
X = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
Y = df['Outcome']

## SCALING AND SPLITING

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_scaled = StandardScaler().fit(X).transform(X)


In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=42)

### Model Fitting

In [7]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()

In [8]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

## Evaluation Function

In [11]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict

In [12]:
def print_score(clf, X_train, X_test, y_train, y_test, train = True):
#     print accuracy score, classification report, confusion metrics
    if train:
#         training performance
        print('Train Result : \n')
        print('Accuracy Score {0:.4f}\n'.format(accuracy_score(y_train, clf.predict(X_train))))
        print('Classification Report : \n {} \n'.format(classification_report(y_train, clf.predict(X_train))))
        print('Confusion Metrics : \n {} \n'.format(confusion_matrix(y_train, clf.predict(X_train))))
        
        res = cross_val_score(clf, X_train, y_train, cv = 10, scoring='accuracy')
        print('Average Accuracy : {0:.4f}\n'.format(np.mean(res)))
        print('Accuracy SD : {0:.4f}\n'.format(np.std(res)))
        
    elif train == False:
#         test performance
        print('Test Result : \n')
        print('Accuracy Score {0:.4f}\n'.format(accuracy_score(y_test, clf.predict(X_test))))
        print('Classification Report : \n {}\n'.format(classification_report(y_test, clf.predict(X_test))))
        print('Confusion Metrics : \n {} \n'.format(confusion_matrix(y_test, clf.predict(X_test))))

## Performance Report

In [13]:
print_score(clf, X_train, X_test, Y_train, Y_test, train = True)

Train Result : 

Accuracy Score 1.0000

Classification Report : 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       401
          1       1.00      1.00      1.00       213

avg / total       1.00      1.00      1.00       614
 

Confusion Metrics : 
 [[401   0]
 [  0 213]] 

Average Accuracy : 0.7150

Accuracy SD : 0.0348



In [14]:
print_score(clf, X_train, X_test, Y_train, Y_test, train = False)

Test Result : 

Accuracy Score 0.7532

Classification Report : 
              precision    recall  f1-score   support

          0       0.83      0.78      0.80        99
          1       0.64      0.71      0.67        55

avg / total       0.76      0.75      0.76       154


Confusion Metrics : 
 [[77 22]
 [16 39]] 



## Now Applying Results Achieved from Feature Selection

In [16]:
X = df[['Glucose', 'BloodPressure', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']]
Y = df['Outcome']

In [17]:
X_scaled = StandardScaler().fit(X).transform(X)

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=42)

In [19]:
clf.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
print_score(clf, X_train, X_test, Y_train, Y_test, train = True)

Train Result : 

Accuracy Score 1.0000

Classification Report : 
              precision    recall  f1-score   support

          0       1.00      1.00      1.00       401
          1       1.00      1.00      1.00       213

avg / total       1.00      1.00      1.00       614
 

Confusion Metrics : 
 [[401   0]
 [  0 213]] 

Average Accuracy : 0.6988

Accuracy SD : 0.0345



In [21]:
print_score(clf, X_train, X_test, Y_train, Y_test, train = False)

Test Result : 

Accuracy Score 0.7273

Classification Report : 
              precision    recall  f1-score   support

          0       0.81      0.75      0.78        99
          1       0.60      0.69      0.64        55

avg / total       0.74      0.73      0.73       154


Confusion Metrics : 
 [[74 25]
 [17 38]] 

