In [123]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
sns.set(color_codes=True)

In [124]:
df = pd.read_csv('diabetes.csv')

In [125]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [126]:
from sklearn.linear_model import LogisticRegression

In [127]:
lR= LogisticRegression()
col_select = ['Pregnancies', 'Glucose','BloodPressure','BMI','DiabetesPedigreeFunction','Age'] 

In [185]:
X = df[col_select]
Y = df['Outcome']

In [148]:
from sklearn.model_selection import train_test_split

In [149]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [150]:
lR.fit(X_train,Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [151]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score

In [152]:
def print_score(clf, X_train, X_test, Y_train, Y_test, train = True):
#     print accuracy score, classification report, confusion metrics
    if train:
#         training performance
        print('Train Result : \n')
        print('Accuracy Score {0:.4f}\n'.format(accuracy_score(Y_train, lR.predict(X_train))))
        print('Classification Report : \n {} \n'.format(classification_report(Y_train, lR.predict(X_train))))
        print('Confusion Metrics : \n {} \n'.format(confusion_matrix(Y_train, lR.predict(X_train))))
        
        res = cross_val_score(lR, X_train, Y_train, cv = 10, scoring='accuracy')
        print('Average Accuracy : {0:.4f}\n'.format(np.mean(res)))
        print('Accuracy SD : {0:.4f}\n'.format(np.std(res)))
        
    elif train == False:
#         test performance
        print('Test Result : \n')
        print('Accuracy Score {0:.4f}\n'.format(accuracy_score(Y_test, clf.predict(X_test))))
        print('Classification Report : \n {}\n'.format(classification_report(Y_test, clf.predict(X_test))))
        print('Confusion Metrics : \n {} \n'.format(confusion_matrix(Y_test, clf.predict(X_test))))

In [163]:
print_score(lR, X_train, X_test, Y_train, Y_test, train = True)
# X_train.shape

Train Result : 

Accuracy Score 0.6401

Classification Report : 
              precision    recall  f1-score   support

          0       0.64      1.00      0.78       393
          1       0.00      0.00      0.00       221

avg / total       0.41      0.64      0.50       614
 

Confusion Metrics : 
 [[393   0]
 [221   0]] 

Average Accuracy : 0.6447

Accuracy SD : 0.0278



/home/shivam/.conda/envs/irisproject/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [154]:
df.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [155]:
lR.coef_

array([[ 0.08904729,  0.02561322, -0.01747394,  0.05770684,  0.60673762,
         0.01143284]])

In [166]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [157]:
from sklearn import preprocessing

In [183]:

X_normalized = preprocessing.normalize(X_train, norm='l1')
X_normalized2 = preprocessing.normalize(X_test, norm='l2')


X = X_normalized




In [162]:
print_score(lR, X_train, X_test, Y_train, Y_test, train = True)

Train Result : 

Accuracy Score 0.6401

Classification Report : 
              precision    recall  f1-score   support

          0       0.64      1.00      0.78       393
          1       0.00      0.00      0.00       221

avg / total       0.41      0.64      0.50       614
 

Confusion Metrics : 
 [[393   0]
 [221   0]] 

Average Accuracy : 0.6447

Accuracy SD : 0.0278



/home/shivam/.conda/envs/irisproject/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [140]:
print_score(lR, X_train, X_test, Y_train, Y_test, train = False)

Test Result : 

Accuracy Score 0.6948

Classification Report : 
              precision    recall  f1-score   support

          0       0.69      1.00      0.82       107
          1       0.00      0.00      0.00        47

avg / total       0.48      0.69      0.57       154


Confusion Metrics : 
 [[107   0]
 [ 47   0]] 



/home/shivam/.conda/envs/irisproject/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [187]:
max_abs_scaler = preprocessing.MaxAbsScaler()
X_train_maxabs = max_abs_scaler.fit_transform(X)

X = X_train_maxabs




In [194]:
X = pd.DataFrame(X)

In [195]:
X.describe()

0           1           2           3           4           5
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000
mean     0.226180    0.607510    0.566438    0.476790    0.194990    0.410381
std      0.198210    0.160666    0.158654    0.117499    0.136913    0.145188
min      0.000000    0.000000    0.000000    0.000000    0.032231    0.259259
25%      0.058824    0.497487    0.508197    0.406855    0.100723    0.296296
50%      0.176471    0.587940    0.590164    0.476900    0.153926    0.358025
75%      0.352941    0.704774    0.655738    0.545455    0.258781    0.506173
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000